game_to_save/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mario', include('mario_dub.urls')),
    path('', include('users.urls')),

]

mario_dub/urls.py
from django.urls import path
from . import views
from django.views.generic import View

app_name = "mario"

urlpatterns = [
    path("", views.home, name= "home")
]

users/urls.py
from os import name
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

app_name = 'users'

urlpatterns = [
    path('home/', views.home.as_view(), name='home'),
    path('register', views.register, name='register'),
    path('', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile.as_view(), name='user-profile'),


]

mario_dub/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.db.models.base import Model
from django.contrib.auth.models import User
import Pillow

# Create your models here.

class game_post(models.Model):
    title = models.CharField(max_length=500, default=None, null=False)
    discreption = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpeg", upload_to="profile_pics")

    def __str__(self):
        return f'{self.user.username} Profile' 

users/forms.py
from django import forms
from django.contrib.auth import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class userRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

mario_dub/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.list import ListView
# Create your views here.

def home(request):
    return render(request, "mario_dub/home.html")

users/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.views.generic import View, ListView, TemplateView
from django.urls import reverse_lazy
from .forms import userRegistrationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import game_post

# Create your views here.

class home(LoginRequiredMixin, ListView):
    model = game_post
    raise_exception = True
    template_name = 'users/home.html'
    queryset = game_post.objects.all()

class profile(LoginRequiredMixin, TemplateView):
    template_name = "users/profile.html"


def register(request):
    
    if request.method == "POST":
        form = userRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f'Account created for {username}!')
            return redirect('users:login')
    else:        
        form = userRegistrationForm()
    return render(request, "users/register.html", {"form": form})

mario_dub/templates/mario_dub/base.html
{% load static %}

<!DOCTYPE html>

<head>
    {%block title%}
    {%endblock%}

    <!-- For responsive design -->
    <meta name="viewport" content="width=device-width, initial-sacle=1">
    <!-- Linking of the stylesheets -->
    <link rel="stylesheet" href="{%static 'mario_dub/css/styles.css'%}">
    <!-- Linking to the bootstrap stylesheet -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
    {% if messages %}
    {%for message in messages %}
        <div class="alert alert-{{message.tags}}"> {{message}} </div>
    {%endfor%}
    {%endif%}
    {%block content%}
    {%endblock%}
</body>

mario_dub/templates/mario_dub/home.html
{%extends "mario_dub/base.html"%}

{%block content%}
    <h1> Hello World! </h1>
{%endblock%}

users/templates/users/base.html
{%load static%}

<!DOCTYPE html>

<html lang = "english">
    <head>

        <!-- Loading the meta view port -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <!-- the title block -->
        {%block title%}
        {%endblock%}

        <!-- Linking to the bootstrap stylesheet -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

         <!-- Link to the local style sheets -->
         <link rel="stylesheet", href="{%static 'users/css/styles.css'%}">
    </head>

    <body>
        
        <!-- Creating the navigation bar -->
<div class="topnav" id="top-nav-bar">
    {%if user.is_authenticated %}
    <a href = "{%url 'users:home'%}"> Home </a>
    <a href = "{%url 'users:logout'%}"> Logout </a>
    <a href = "{%url 'users:user-profile'%}"> Profile </a>
    {% else %}
    <a href = "{%url 'users:register'%}"> Register </a>
    <a href = "{%url 'users:login'%}"> Login </a>
    {%endif%}
    <a class="icon" onclick="myFunction()"><i class="fa fa-chevron-circle-down" aria-hidden="true"></i>
        </a>

</div>
        
        {% if messages %}
            {%for message in messages %}
                <div class="alert alert-{{message.tags}}"> {{message}} </div>
            {%endfor%}
        {%endif%}
        {%block content%}
        {%endblock%}
    </body>

    <!-- Adding the scripts here -->
    <script>
        function myFunction() 
        {
            var x = document.getElementById("top-nav-bar");
            if (x.className === "topnav") 
            {
                x.className += " responsive";
            } 
            else 
            {
                x.className = "topnav";
            }
        }
    </script>

</html>

users/templates/users/home.html
{%extends "users/base.html"%}

{%block title%}
    <title>Home</title>
{%endblock%}

{%block content%}
    <span> Welcome </span>
    <a href="{%url 'users:logout' %}"> Logout </a>
{%endblock%}

users/templates/users/login.html
{%extends "users/base.html"%}
{%load crispy_forms_tags %}
{%block content%}

<div class="register-parent">

   <div class="register-parent2">
        <form method="POST">
            <!-- including the csrf token -->
            {%csrf_token%}
            <fieldset class="">
                <legend class="register-heading"> Login </legend>
                {{form|crispy}}
            </fieldset>

            <div id="submit-parent">
                <button type="submit" class="submit"> Login </button>
            </div>
        </form>
    </div>
    <div id="already-account">
        <span> Don't have an account! </span>
        <a class="link" href="{%url 'users:register' %}"> Register </a>
    </div>
</div>



{%endblock%}

users/templates/users/logout.html
{%extends "users/base.html"%}

{%block content%}

<div class="register-parent">
    <div id="already-account">
        <span> Logout Sucessfull! </span>
        <a class="link" href="{%url 'users:login' %}"> Login </a>
    </div>
</div>

{%endblock%}

users/templates/users/profile.html
{%extends "users/base.html"%}
{%block content%}
    <h1> {{user.username}}</h1>
{%endblock%}

users/templates/users/register.html
{%extends "users/base.html"%}
{%load crispy_forms_tags %}
{%block content%}

<div class="register-parent">

   <div class="register-parent2">
        <form method="POST">
            <!-- including the csrf token -->
            {%csrf_token%}
            <fieldset class="">
                <legend class="register-heading"> Join Today </legend>
                {{form|crispy}}
            </fieldset>

            <div id="submit-parent">
                <button type="submit" class="submit"> Register </button>
            </div>
        </form>
    </div>
    <div id="already-account">
        <span> Already have an account </span>
        <a class="link" href="{%url 'users:login' %}"> Sign in </a>
    </div>
</div>



{%endblock%}